### ISSUE TITLE
Add promise concept in javascript

### ISSUE THREAD

**Issue by pankajdeh** [Aman22sharma/Hacktoberfest2023-beginner#23]

**Comment by code-bajju** [comment]
@Aman22sharma @pankajdeh I'm in! I'll Add promise concept in javascript, and keep it clean according to my expertise. Assign me for this!

**Comment by parastopwal07** [comment]
Please assign me this

**Comment by Aman22sharma** [comment]
@parastopwal07 we already have an open issue that you can contribute to it.
